#!/bin/sh
# Changes the brightness depending on the passed parameter:
# - "inc": Increses the brightness
# - "dec": Decreases the brightness
# - otherwise: Does nothing
#
# Afterwards, shows a notification displaying the current brightness
# of the screen

brightness_change=$1
if [ "$brightness_change" = "inc" ]; then
    xbacklight -inc 10
elif [ "$brightness_change" = "dec" ]; then
    xbacklight -dec 10
fi

current_brightness=$(xbacklight -get | sed 's/\.[0-9]*//g')

if [ "$current_brightness" -le 17 ]; then
	icon="images/brightness-1.png"
elif [ "$current_brightness" -le 33 ]; then
	icon="images/brightness-2.png"
elif [ "$current_brightness" -le 50 ]; then
	icon="images/brightness-3.png"
elif [ "$current_brightness" -le 67 ]; then
	icon="images/brightness-4.png"
elif [ "$current_brightness" -le 83 ]; then
	icon="images/brightness-5.png"
else
	icon="images/brightness-6.png"
fi

notify-send --urgency=normal \
    --expire-time=1500 \
    -i ~/.local/bin/notifications/$icon \
    --hint="int:value:${current_brightness}" \
    -- "Brightness"
