#!/bin/sh
#
# Usage: brightness-notification [inc|dec]
#
# Changes the brightness depending on the passed parameter:
# - "inc": Increses the brightness
# - "dec": Decreases the brightness
# - otherwise: Does nothing
#
# Afterwards, shows a notification displaying the current brightness
# of the screen

brightness_change=$1
if [ "$brightness_change" = "inc" ]; then
    set-brightness -i 10
elif [ "$brightness_change" = "dec" ]; then
    set-brightness -d 10
fi

current_brightness=$(get-brightness)
max_brightness=$(get-max-brightness)
brightness_perc=$(echo "$current_brightness * 100 / $max_brightness" | bc)

if [ "$brightness_perc" -le 17 ]; then
	icon="images/brightness-1.png"
elif [ "$brightness_perc" -le 33 ]; then
	icon="images/brightness-2.png"
elif [ "$brightness_perc" -le 50 ]; then
	icon="images/brightness-3.png"
elif [ "$brightness_perc" -le 67 ]; then
	icon="images/brightness-4.png"
elif [ "$brightness_perc" -le 83 ]; then
	icon="images/brightness-5.png"
else
	icon="images/brightness-6.png"
fi

notify-send --urgency=normal \
    --expire-time=1500 \
    -i ~/.local/bin/notifications/$icon \
    --hint="string:desktop-entry:brightness-notification" \
    --hint="int:value:${brightness_perc}" \
    -- "Brightness"
