#!/bin/sh
# Changes the foreground color of the images into a
# yellowish tint and saves the result in another file

convert brightness-1-original.png +level-colors transparent,"#ebdbb2" brightness-1.png
convert brightness-2-original.png +level-colors transparent,"#ebdbb2" brightness-2.png
convert brightness-3-original.png +level-colors transparent,"#ebdbb2" brightness-3.png
convert brightness-4-original.png +level-colors transparent,"#ebdbb2" brightness-4.png
convert brightness-5-original.png +level-colors transparent,"#ebdbb2" brightness-5.png
convert brightness-6-original.png +level-colors transparent,"#ebdbb2" brightness-6.png
convert brightness-7-original.png +level-colors transparent,"#ebdbb2" brightness-7.png
