#!/bin/sh
# Returns all connected devices in a list with the following format:
# <adress> <battery-level> <device-name>
#
# Example:
# 0A:56:56:A4:77:26 100% My Headphones 1
# 0A:62:65:E2:28:27 40% My Headphones 2

echo 'devices Connected' | bluetoothctl |
    grep -E '^Device\s*[0-9A-F:]+' |
    while read -r _ id name; do
        battery=$(echo "info $id" | bluetoothctl |
            grep "Battery Percentage" |
            grep -o '([0-9]\+)' |
            tr -d '()')

        echo "$id ${battery}% $name"
    done

