#!/bin/sh
# Prompts the user to select a url from the specified list (using dmenu).
# The selected url will be copied or opened.

urlregex="(((http|https|gopher|gemini|ftp|ftps|git|mailto)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)"
urls="$(sed 's/.*│//g' | tr -d '\n' |		# First remove linebreaks and mutt sidebars
	grep -aEo "$urlregex" |					# grep only urls as defined above
	uniq |									# Ignore neighboring duplicates
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")"				# xdg-open will not detect url without http

[ -z "$urls" ] && exit 1

while getopts "hoc" o
do
	case "${o}" in
		h) printf "ARGUMENTS:\\n\t-o: xdg-open (default)\\n\\t-c: copy\\n\\t -h: Show this message\\n" && exit 1 ;;
		o) chosen="$(echo "$urls" | dmenu -i -p "Open:" -l 10)"
			setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
		c) echo "$urls" | dmenu -i -p "Copy:" -l 10 | tr -d '\n' | xclip -selection clipboard ;;
		*) printf "Invalid option -$s\\nTry '-h' for more information.\n" "$OPTARG" && exit 1 ;;
	esac
done
