#!/bin/sh
# Returns the mime-type of the passed file.
# This is done by first checking the extension of the file (e.g. *.txt) if
# present and then checking the contents of the file using 'file --mime-type'

file_name="$1"
file_ext="$(basename "$file_name" | tr '[:upper:]' '[:lower:]')"

case "$file_ext" in
    *.tar*)
        file_type="application/x-tar"
        ;;
    *.zip)
        file_type="application/zip"
        ;;
    *.rar)
        file_type="application/vnd.rar"
        ;;
    *.7z)
        file_type="application/x-7z-compressed"
        ;;
    *.avi)
        file_type="video/x-msvideo"
        ;;
    *.mp4)
        file_type="video/mp4"
        ;;
    *.mpeg)
        file_type="video/mpeg"
        ;;
    *.pdf)
        file_type="application/pdf"
        ;;
    *.jpg|*.jpeg)
        file_type="image/jpg"
        ;;
    *.png)
        file_type="image/png"
        ;;
    *.bmp)
        file_type="image/bmp"
        ;;
    *.svg)
        file_type="image/svg+xml"
        ;;
    *.gif)
        file_type="image/gif"
        ;;
    *.txt|*.lua)
        file_type="text/plain"
        ;;
    *.html|*.htm)
        file_type="text/html"
        ;;
    *.md)
        file_type="text/markdown"
        ;;
    *.xml)
        file_type="application/xml"
        ;;
    *.odp)
        file_type="application/vnd.oasis.opendocument.presentation"
        ;;
    *.ods)
        file_type="application/vnd.oasis.opendocument.spreadsheet"
        ;;
    *.odt)
        file_type="application/vnd.oasis.opendocument.text"
        ;;
    *.c)
        file_type="text/x-c"
        ;;
    *.cpp)
        file_type="text/x-c++"
        ;;
    *.h)
        file_type="text/x-c"
        ;;

    # Custom file types
    *.desktop)
        file_type="application/desktop-entry"
        ;;
esac

if [ -z "$file_type" ]; then
    file_type="$(file --mime-type --brief --dereference -- "$file_name")"
fi

echo "$file_type"
