#!/bin/sh
# Normalizes the name of the spcified file by following some
# criteria:
# Only lowercase letters, no spaces, ...

input_file="$1"
if [ -z "$input_file" ]; then
	read input_file
fi

echo "Original:\t$input_file"

normalized_file=$(echo $input_file |
	sed "s/'//g" |
	sed 's/\- /-/g' |
	sed 's/ \-/-/g' |
	tr ' ' '-' |
	tr '[:upper:]' '[:lower:]')

echo "Normalized:\t$normalized_file"

if [ "$input_file" = $normalized_file ]; then
	echo "The original file is the same as the normalized file (skipping)"
else
	mv "$input_file" $normalized_file
fi
