#!/bin/sh
# Get all image files and show them in nsxiv
# Default: Sorted by their modification time (newest first)
# -r: Random order

random_order=false

while getopts "r" o
do
    case "$o" in
        r) random_order=true ;;
    esac
done

create-thumbnails

image_files=$(find . -maxdepth 2 -type f \
        -regextype "posix-extended" \
        -iregex ".*\.jpg|.*\.jpeg|.*\.png|.*\.webp|.*\.bmp|.*\.tiff|.*\.tif|.*\.raw|.*\.ico|.*\.exif|.*\.heic|.*\.heif|.*\.gif|.*\.avif|.*\.jxl" \
        -printf "%T+ %p\n")


if [ "$random_order" = true ]; then
    echo "$image_files" \
        | shuf \
        | awk '{print $2}' \
        | nsxiv --stdin --thumbnail --scale-mode=f --animate --quiet --private
else
    echo "$image_files" \
        | sort --reverse \
        | awk '{print $2}' \
        | nsxiv --stdin --thumbnail --scale-mode=f --animate --quiet --private
fi

