#!/bin/sh
# Lets the user select a region or window, makes a screenshot of it
# and saves it in the folder specified by the $SCRNSHOT_DIR environment
# variable.
# Pass 'all' as the first argument to take a screenshot of the whole screen.

scrnshot_dir=$(echo $SCRNSHOT_DIR | sed "s/\/$//g")
date_time_stamp=$(date +%Y-%m-%d-%H%M%S)
scrnshot_name="${scrnshot_dir}/${date_time_stamp}.png"

if [ "$1" = "all" ]; then
    maim "$scrnshot_name" --hidecursor &&
        xclip -selection clipboard -t image/png -i "${scrnshot_name}" &&
        notify-send -u normal -t 2000 \
            -i "${scrnshot_name}" \
            "Screenshot taken" "Saved in ${scrnshot_dir}"
else
    maim --select ${scrnshot_dir}/${date_time_stamp}.png --hidecursor &&
        xclip -selection clipboard -t image/png -i "${scrnshot_name}" &&
        notify-send -u normal -t 2000 \
            -i "${scrnshot_name}" \
            "Screenshot taken" "Saved in ${scrnshot_dir}"
fi
