#!/bin/sh
# Sets the brightness to the passed value if the current brightness
# is higher than this value

current_brightness=$(xbacklight -get | sed 's/\.[0-9]*//g')

if [ "$1" -lt "$current_brightness" ]; then
    $(xbacklight -set "$1" -time 1000)
fi
