#!/bin/sh

# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.

wallpaper_link="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
new_wallpaper="$(readlink -f "$1")" &&

case "$(file --mime-type -b "$new_wallpaper")" in
	image/* )
		ln -sf "$new_wallpaper" "$wallpaper_link" &&
			notify-send -t 3000 -i "$wallpaper_link" "Wallpaper changed"
		;;
	inode/directory )
		new_wallpaper_file="$(
			find "$new_wallpaper" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f |
			shuf -n 1
		)"
		ln -sf "$new_wallpaper_file" "$wallpaper_link" &&
			notify-send -t 3000 -i "$wallpaper_link" "Random Wallpaper chosen"
		;;
	*) notify-send -t 3000 "Error" "Not a valid image" ; exit 1;;
esac

# Apply wallpaper
xwallpaper --zoom "$wallpaper_link"

