#!/bin/sh
# Set keyboard settings
# - Set layout to at:nodeadkeys and us:dvorak
# - Toggle layout with Alt+Shift
# - Replace comma with dot on numpad
# - Swap CAPS and ESC keys
# - Setup key bindings using AltGr
setxkbmap -layout at,us \
	-variant nodeadkeys,dvorak \
	-option "grp:alt_shift_toggle" \
	-option "kpdl:dot" \
	-option "caps:swapescape" && \
    xmodmap -e "keycode 28 = t T t T asciitilde" && \
    xmodmap -e "keycode 38 = a A a A braceleft" && \
    xmodmap -e "keycode 39 = s S s S braceright" && \
    xmodmap -e "keycode 40 = d D d D bracketleft" && \
    xmodmap -e "keycode 41 = f F f F bracketright" && \
    xmodmap -e "keycode 42 = g G g G backslash" && \
    xmodmap -e "keycode 56 = b B b B backslash"
