#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $(basename "$0") <username> <password>"
    exit 1
fi

CONNAME="eduroam"
USERNAME="$1"
PASSWORD="$2"

nmcli connection add type wifi \
con-name $CONNAME \
connection.permissions $LOGNAME \
802-11-wireless.ssid $CONNAME \
802-11-wireless-security.key-mgmt wpa-eap \
802-11-wireless-security.group ccmp,tkip \
802-11-wireless-security.pairwise ccmp \
802-11-wireless-security.proto rsn \
802-1x.eap peap \
802-1x.identity $USERNAME \
802-1x.password $PASSWORD \
802-1x.phase2-auth mschapv2

