#!/bin/sh
# Requires ffmpeg (audio splitting) and my `tag-audio` wrapper script.

[ ! -f "$2" ] && printf "The first file should be the audio, the second should be the timecodes.\\n" && exit

echo "Enter the album title:"; read -r album_title

echo "Enter the artist/author:"; read -r author

echo "Enter the publication year:"; read -r year

inputaudio="$1"

album_dir_name="$(echo "$album_title" |
	iconv -cf UTF-8 -t ASCII//TRANSLIT |
	tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' |
	tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
! mkdir -p "$album_dir_name" && echo "Do you have write access in this directory?" && exit 1

# As long as the extension is in the tag-audio script, it'll work.
file_extension="opus"
#file_extension="${1#*.}"

# Get the total number of tracks from the number of lines.
number_of_tracks="$(wc -l < "$2")"

while read -r x
do
	end="$(echo "$x" | cut -d' ' -f1)"

	[ -n "$start" ] &&
		echo "From $start to $end; $track $title"

	file="$album_dir_name/$(printf "%.2d" "$track")-$esctitle.$file_extension"

	[ -n "$start" ] && echo "Splitting \"$title\"..." &&
		ffmpeg -nostdin -y -loglevel -8 -i "$inputaudio" -ss "$start" -to "$end" -vn -c copy "$file" &&
		echo "Tagging \"$title\"..." && tag-audio -a "$author" -A "$album_title" -t "$title" -n "$track" -N "$number_of_tracks" -d "$year" "$file"

	title="$(echo "$x" | cut -d' ' -f 2-)"
	esctitle="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
	track="$((track+1))"
	start="$end"
done < "$2"

# The last track must be done outside the loop.
echo "From $start to the end: $title"
file="$album_dir_name/$(printf "%.2d" "$track")-$esctitle.$file_extension"

echo "Splitting $title..." &&
	ffmpeg -y -loglevel -8 -i "$inputaudio" -ss "$start" -vn -c copy "$file" &&
	echo "Tagging $title..." &&
	tag-audio -a "$author" -A "$album_title" -t "$title" -n "$track" -N "$number_of_tracks" -d "$year" "$file"
