#!/bin/sh
# Downloads the audio track of a youtube video using youtube-dl
# and normalizes its file name (replaces special characters, etc.).

youtube-dl --add-metadata --ignore-errors --extract-audio \
	--output '___---%(title)s.%(ext)s' \
	--restrict-filenames \
	-- "$1"

created_files=$(ls | grep '^___---.*$')

echo "$created_files" | while read -r file_name
do
    new_file_name=$(echo "$file_name" | cut -c7-)
    mv "$file_name" "$new_file_name"
    normalize-file-name "$new_file_name"
done

