#!/bin/sh
# This script will create a backup of my home directory and
# the mounted data filesystem using rsync

backup_drive=/run/media/robert/backup

# Backup home directory
rsync --archive --verbose --update --links --delete --partial --progress --force \
      --exclude-from=/home/robert/.config/rsync/ignore-list \
	  /home/robert/ $backup_drive/home/

# Backup data file system
rsync --archive --verbose --update --links --delete --partial --progress --force \
      --exclude-from=/home/robert/.config/rsync/ignore-list \
	  /mnt/data/ $backup_drive/data/

# Backup local binaries
rsync --archive --verbose --update --links --delete --partial --progress --force \
      --exclude-from=/home/robert/.config/rsync/ignore-list \
	  /usr/local/bin/ $backup_drive/local-bin/

# Create list of explicitly installed programs
pacman -Qe > $backup_drive/installed-programs
