#!/bin/sh

sudo systemctl disable dhcpcd.service
sudo systemctl stop dhcpcd.service

sudo systemctl enable iwd.service
sudo systemctl start iwd.service

sudo systemctl enable wpa_supplicant.service
sudo systemctl start wpa_supplicant.service

sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service

