#!/usr/bin/env sh
# This code originates from:
# https://github.com/slavistan/lf-gadgets
# Changes were made by Robert Lag.

if [-z "$LF_UEBERZUG_TEMPDIR" ]; then
    exit
fi

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

lf-ueberzug-cleaner # clean active preview

preview_width="$(($4 - 2))"
file="$1"; shift
# Use unique thumbnail name each time as otherwise lf won't refresh the preview
thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail-$(basename "$file").png"

case "$(file-type "$file")" in
	text/html)
		lynx -width="$preview_width" -display_charset=utf-8 -dump "$file" ;;
	text/* | */xml | application/json | application/javascript \
        | application/x-sh | application/x-shellscript | application/x-subrip)
		bat --terminal-width "$preview_width" \
			--force-colorization \
			--style="plain,changes" -- "$file" ;;
	application/zip | application/gzip | application/x-tar \
        | application/x-rar-compressed \
		| application/x-zip-compressed | application/x-7z-coompressed)
		atool --list -- "$file" ;;
	audio/* | application/octet-stream)
		mediainfo "$file" ;;
	image/svg+xml)
		gm convert "$file" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	image/gif)
		gm convert "$file[0]" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	image/heic)
        heif-thumbnailer "$file" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	image/*)
		preview "$file" "$@" ;;
	video/*)
		ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	application/pdf)
        if qpdf --requires-password "$file"; then
            printf "\033[0;31m%s\033[0m\n" "*** Password protected ***"
            mediainfo "$file"
        else
            gs -o "$thumbnail" -sDEVICE=png16m -dLastPage=1 -dUseCropBox "$file" >/dev/null
            preview "$thumbnail" "$@"
        fi
		;;
	*opendocument*)
		odt2txt --width="$preview_width" "$file" ;;
	application/pgp-encrypted)
		gpg -d -- "$file" ;;
    application/drawio)
        drawio -x "$file" -o "$thumbnail" --width 960 >/dev/null
        preview "$thumbnail" "$@"
        ;;
	*)
		mediainfo "$file" ;;
esac

# Cleanup thumbnail file
rm -f "$thumbnail"

return 127 # nonzero retcode required for lf previews to reload
