#!/usr/bin/env sh
# This code originates from:
# https://github.com/slavistan/lf-gadgets
# Changes were made by Robert Lag.

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

lf-ueberzug-cleaner # clean active preview

preview_width="$(($4 - 2))"
file="$1"; shift

case "$(file-type "$file")" in
	text/html)
		lynx -width="$preview_width" -display_charset=utf-8 -dump "$file" ;;
	text/* | */xml | application/json | application/x-sh \
        | application/x-shellscript)
		bat --terminal-width "$preview_width" \
			--force-colorization \
			--style="plain,changes" -- "$file" ;;
	application/zip | application/gzip | application/x-tar \
        | application/x-rar-compressed \
		| application/x-zip-compressed | application/x-7z-coompressed)
		atool --list -- "$file" ;;
	audio/* | application/octet-stream)
		mediainfo "$file" ;;
	image/svg+xml)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gm convert "$file" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	image/gif)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gm convert "$file[0]" "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	image/*)
		preview "$file" "$@" ;;
	video/*)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
		preview "$thumbnail" "$@"
		;;
	application/pdf)
		thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
		gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
		preview "$thumbnail" "$@"
		;;
	*opendocument*)
		odt2txt --width="$preview_width" "$file" ;;
	application/pgp-encrypted)
		gpg -d -- "$file" ;;
	*)
		mediainfo "$file" ;;
esac

return 127 # nonzero retcode required for lf previews to reload
