#!/bin/sh
# Sets the brightness to the passed value if the current brightness
# is higher than this value

current_brightness=$(cat "/sys/class/backlight/amdgpu_bl1/brightness")
max_brightness=$(cat "/sys/class/backlight/amdgpu_bl1/max_brightness")

if [ "$1" -lt "$current_brightness" ]; then
    if [ "$1" -lt "$max_brightness" ]; then
        echo "$1" | tee "/sys/class/backlight/amdgpu_bl1/brightness"
    else
        echo "$max_brightness" | tee "/sys/class/backlight/amdgpu_bl1/brightness"
    fi
fi
