#!/bin/sh
# Sets the brightness to the passed value if the current brightness
# is higher than this value

current_brightness=$(cat "/sys/class/backlight/amdgpu_bl1/brightness")
max_brightness=$(cat "/sys/class/backlight/amdgpu_bl1/max_brightness")
new_value=$(echo "$1 * $max_brightness / 100" | bc)

if [ "$new_value" -lt "$current_brightness" ]; then
    if [ "$new_value" -lt "$max_brightness" ]; then
        echo "$new_value" | tee "/sys/class/backlight/amdgpu_bl1/brightness"
    else
        echo "$max_brightness" | tee "/sys/class/backlight/amdgpu_bl1/brightness"
    fi
fi
