#!/bin/bash
# Feed this script a link and it will give dmenu
# some choice programs to use to open it

# The URL will be shown visualle in 30 chars or less
if [[ "${#1}" -gt 30 ]]; then
	visual="${1:0:20}"..."${1: -7}"
else
	visual="$1"
fi

x=$(echo -e "mpv\nbrowser\nlynx" | dmenu -i -p "Open '$visual' in")
case "$x" in
	mpv) mpv -quiet "$1" 2&>/dev/null & disown;;
	browser) $BROWSER "$1" 2&>/dev/null & disown;;
	lynx) lynx "$1" 2&>/dev/null & disown;;
esac
