#!/bin/sh
# Displays all W-LAN routers in the vicinity in a dmenu prompt. If the user
# selects one of them a password prompt is shown or if the router has been
# saved you will be connected to it even without a prompt.

iwctl station wlan0 scan
available_networks=$(iwctl station wlan0 get-networks |
	awk -F '[[:space:]][[:space:]]+' '/./ {
	if(NR > 4)
	{
		printf "%-40s  %4s\n", $2, $4
	}
}' | sed 's/\x1b/#/g' | cut -f1 -d"#")

selected_network=$(echo "$available_networks" | dmenu -l 10)

selected_network_name=$(echo "$selected_network" |
	awk -F '[[:space:]][[:space:]]+' '{ print $1 }')
[ -z "$selected_network_name" ] && exit 1
echo "$selected_network_name"

$TERMINAL -e $SHELL -c "iwctl station wlan0 connect \"${selected_network_name}\""
