#!/bin/sh
# Outputs all songs that are in no playlist or are multiple times in the
# same playlist. By using either the -m or -d flag you can specify that
# only one of these 2 searches are done

while getopts "hmd" o
do
	case "${o}" in
		h) printf "OPTIONS:\\n\t-m: search only for songs with no playlist\\n\\t-d: search for duplicates in playlists\\n\\t-h: Show this message\\n" ;;
		m) exec mpc-playlist-missing-search ;;
		d) exec mpc-playlist-duplicate-search ;;
		*) printf "OPTIONS:\\n\t-m: search only for songs with no playlist\\n\\t-d: search for duplicates in playlists\\n\\t-h: Show this message\\n" ;;
	esac
done

if [ $OPTIND -eq 1 ]; then
	# No options were passed to the script

	missing_search_result=$(mpc-playlist-missing-search)
	if [ -n "$missing_search_result" ]; then
		echo "Songs, which are in no playlist:"
		echo "================================"
		mpc-playlist-missing-search
	fi

	duplicate_search_result=$(mpc-playlist-duplicate-search)

	if [ -n "$duplicate_search_result" ]; then
		if [ -n "$missing_search_result" ]; then
			echo "\n"
		fi

		echo "Songs, which are multiple times in the same playlist:"
		echo "====================================================="
		mpc-playlist-duplicate-search
	fi
fi
