#!/bin/sh

while getopts "hmd" o
do
	case "${o}" in
		h) printf "OPTIONS:\\n\t-m: search only for songs with no playlist\\n\\t-p: search for duplicates in playlists\\n\\t-h: Show this message\\n" ;;
		m) exec mpc-playlist-missing-search ;;
		d) exec mpc-playlist-duplicate-search ;;
		*) printf "OPTIONS:\\n\t-m: search only for songs with no playlist\\n\\t-p: search for duplicates in playlists\\n\\t-h: Show this message\\n" ;;
	esac
done

if [ $OPTIND -eq 1 ]; then
	# No options were passed to the script

	echo "Songs, which are in no playlist:"
	echo "================================"
	mpc-playlist-missing-search

	echo "Songs, which are multiple times in the same playlist:"
	echo "====================================================="
	mpc-playlist-duplicate-search
fi
