#!/bin/sh
# Outputs all songs in mpc which are multiple times in the same playlist

all_playlist_names=$(mpc lsplaylists)

while IFS= read -r playlist_name
do
	songs_in_current_playlist=$(mpc --format "%title%" playlist "$playlist_name" | sort)
	duplicate_songs_in_current_playlist=$(printf '%s\n' "$songs_in_current_playlist" | uniq -d)

	if [ -n "$duplicate_songs_in_current_playlist" ]; then
		printf '%s\n%s\n\n' "$playlist_name:" "$duplicate_songs_in_current_playlist"
	fi
done << EOF
$all_playlist_names
EOF
