#!/bin/sh
# Shows a notification displaying information about
# the currently playing song (using mpc)
# Optionally the duration the notification should be displayed
# can be passed to the script.

current_song=$(mpc current --format "%title%")
artist=$(mpc current --format "%artist%")
album=$(mpc current --format "%album%")
if echo $1 | grep -Eq '^[0-9]+$'; then
    show_duration=$1
else
    show_duration=3000
fi

if [ -n "$current_song" ]; then
	directory=$(dirname $(mpc current --format "%file%"))
fi
icon_path=~/music/${directory}/AlbumArt.jpg
if [ ! -e $icon_path ]; then
    icon_path="~/music/AlbumArt.jpg"
fi

message_title="$current_song"

	message="$artist"

notify-send -u normal -t "$show_duration" \
    --replace-id=1001 \
    --icon="$icon_path" \
    -- "$message_title" "$message"
